/*

  Includes:

  Sizzle CSS Selector Engine
  Copyright 2011, The Dojo Foundation
  Released under the MIT, BSD, and GPL Licenses.
  More information: http://sizzlejs.com/
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2013 VigLink. Rights reserved and patent(s) pending.
*/
(function(f){var j,c;c={_breaker:{},each:function(a,d){var h,b;if("object"===c.type(a)&&a.hasOwnProperty)for(h in a){if(a.hasOwnProperty(h)&&d(a[h],h)===c._breaker)break}else{h=0;for(b=a.length;h<b&&d(a[h],h)!==c._breaker;h++);}},extend:function(a){var d,h,b,c,k=arguments.length;a=a||{};for(h=1;h<k;h++)if(c=arguments[h],void 0!==c&&null!==c)for(b in c)d=c[b],a!==d&&void 0!==d&&(a[b]=d);return a},noop:function(){},type:function(a){return null===a?"null":void 0===a?"undefined":("object"===typeof HTMLElement?
a instanceof HTMLElement:a&&"object"===typeof a&&null!==a&&1===a.nodeType&&"string"===typeof a.nodeName)?"element":Object.prototype.toString.call(a).slice(8,-1).toLowerCase()}};c.extend(c,{addClass:function(a,d){c.hasClass(a,d)||(a.className=(a.className?a.className+" ":"")+d)},attrValues:function(a,d,h){return(d=a[d])?d.split(h||" "):[]},bind:function(a,d){return function(){return a.apply(d,arguments)}},browser:function(){var a={},d,h=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,
"$1; ").replace(/\;\s*$/,"").split(/;\s*/);c.each(h,function(h){d=(/[\/ :]([^\/ :]+)$/.exec(h)||[])[1];a[d?h.substr(0,h.length-d.length-1).replace(/\d*$/,""):h]=d||!0});return{aol:a.aol,blackberry:a.blackberry,ie:a.msie,ios:a.mobile&&a.safari,opera:a.opera,playstation:a.playstation,version:parseFloat(a.version||a.crios)||!1}}(),cache:function(){var a={},d="vglnk_"+(new Date).getTime(),h=0;return function(b,c,k){if(b){var o=b[d];if(o||void 0!==k)return o||(o=++h),a[o]||(b[d]=o,a[o]={}),void 0!==k&&
(a[o][c]=k),"string"===typeof c?a[o][c]:a[o]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=c.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return c.extend({},a)},contains:function(a,d){return-1!==c.indexOf(a,d)},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a){for(var d=window.self;d.parent&&d.parent!==d;)if(d=d.parent,d===
a)return!0;return!1},cors:function(a){var d,h=function(){eval(d.responseText)};d=new window.XMLHttpRequest;d.onreadystatechange=function(){4===d.readyState&&200===d.status&&h()};try{d.open("GET",a),d.withCredentials=!0,d.send()}catch(b){return!1}},createA:function(a,d){return c.createEl("a",{href:a,target:d})},createEl:function(a,d,h,b){var g;a=(b||document).createElement(a);d=d||{};h=h||{};for(g in d)void 0!==d[g]&&(a[g]=d[g]);c.css(a,h);return a},css:function(a,d){for(var h in d)try{a.style[h]=
d[h]}catch(b){}return a},destructing:function(a){var d=!1,h;return function(){d||(h=a.apply(null,arguments),d=!0);return h}},escapeRegExp:function(){var a;return function(d){a=a||RegExp("([.*+?^${}()|[\\]\\\\])","g");return d.replace(a,"\\$1")}}(),eventLink:function(a){var d,h=a.target||a.srcElement;do{try{d=h.nodeType}catch(b){break}if(1===d&&(a=h.tagName.toUpperCase(),"A"===a||"AREA"===a))return h;h=h.parentNode}while(h)},exceptionLogger:function(){var a=!1,d=c.noop;return function(h,b){if(void 0!==
b)a=b,d=h;else return function(){if(a)try{return h.apply(this,arguments)}catch(b){d(b)}else return h.apply(this,arguments)}}}(),find:function(a,d){var b;c.each(a,function(a,g){if(d(a,g))return b=a,c._breaker});return b},generateNodeFilter:function(){var a=function(a,d){var b,c;d=","+d.join(",")+",";b=0;for(c=a.length;b<c;b++)if(-1!==d.indexOf(","+a[b]+","))return!0;return!1},d=function(a,d){var b=a.nodeName.toLowerCase();return-1!==d.indexOf(","+b+",")};return function(b){b=c.extend({custom:null,
classes:[],rels:[],tags:[]},b);b.tags.length&&(b.tags=","+b.tags.join(",").toLowerCase()+",");return function(i,g){g=c.extend({ancestors:!0,self:!0},g);var k=!0,o=!0,e=function(i,g){var k;if(k=!(b.tags.length&&d(i,b.tags))){if(k=b.classes.length){k=b.classes;var o=c.attrValues(i,"className");k=a(k,o)}if(k=!k){if(k=b.rels.length)k=b.rels,o=c.attrValues(i,"rel"),k=d(i,",a,")&&a(k,o);k=!k&&!("function"===c.type(b.custom)&&b.custom(i,g))}}return k},o=!g.self||e(i,!0);if(g.ancestors)for(;i.parentNode;)if(i=
i.parentNode,1===i.nodeType&&!e(i,!1)){k=!1;break}return o&&k}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("\x26");var d={};c.each(a,function(a){a=a.split("\x3d");d[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return d},geometry:function(){var a,d=arguments.length,b=Infinity,i=Infinity,g=-Infinity,k=-Infinity,o;for(a=0;a<d;a++)o=c.position(arguments[a]),b=Math.min(b,o.x),i=Math.min(i,o.y),g=Math.max(g,o.x+arguments[a].offsetWidth),k=Math.max(k,o.y+arguments[a].offsetHeight);
return{x:b,y:i,w:g-b,h:k-i,x1:b,y1:i,x2:g,y2:k}},getActualHref:function(a){return c.cache(a,"href")||a.href},hasAttrValue:function(a,d,b,i){return d?c.contains(c.attrValues(a,d,i),b):!1},hasClass:function(a,d){return c.hasAttrValue(a,"className",d)},hasRel:function(a,d){return c.hasAttrValue(a,"rel",d)},indexOf:Array.prototype.indexOf?function(a,d){return Array.prototype.indexOf.call(a,d)}:function(a,d){var b,c;b=0;for(c=a.length;b<c;b++)if(a[b]===d)return b;return-1},isArray:function(a){return"array"===
c.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var d=document.getElementsByTagName("script")[0];a=c.createEl("script",{type:"text/javascript",src:a});d.parentNode.insertBefore(a,d)},map:function(a,d){var b=[];c.each(a,function(a,c){void 0!==a&&(b[c]=d(a))});return b},on:function(){var a;return function(d,b,i){var g,k;if(1===arguments.length)a=d;else{if(2===arguments.length){if(!a)return;
i=b;b=d;d=a}try{g=d["on"+b]}catch(o){}"function"===typeof g&&(d["on"+b]=c.bind(function(a){a=a||window.event;var b=g.apply(d,arguments);this.exceptionLogger(function(){return a?(void 0!==b&&!1!==a.returnValue&&(a.returnValue=b),c.isDefaultPrevented(a)&&"function"===c.type(a.preventDefault)&&a.preventDefault(),a.returnValue):b})()},this));k=c.exceptionLogger(function(){if(a.enabled())return i.apply(null,arguments)});d.addEventListener?d.addEventListener(b,k,!1):d.attachEvent&&d.attachEvent("on"+b,
k)}}}(),position:function(a){var d,b=0,c=0,g=0,k=0;if(!a.offsetParent)return!1;d=a;do b+=d.offsetLeft,c+=d.offsetTop,d=d.offsetParent;while(d);d=a;do g+=d.scrollLeft,k+=d.scrollTop,d=d.parentNode;while(d&&d!==document.body);return{x:b-g,y:c-k}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},ready:function(){var a=!1,d=[],b=!1,i,g,k,o,e;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",k,!1);e()}:document.attachEvent&&(o=
function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",o),e())});i=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return e();if(document.addEventListener)document.addEventListener("DOMContentLoaded",k,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",o);var d=!1;try{d=null===window.frameElement}catch(b){}document.documentElement.doScroll&&d&&g()}c.on(window,"load",e)}};g=function(){if(!b){try{document.documentElement.doScroll("left")}catch(a){setTimeout(c.exceptionLogger(g),
1);return}e()}};e=function(){if(!b){if(!document.body)return setTimeout(c.exceptionLogger(e),13);b=!0;d&&(c.each(d,function(a){a()}),d=null)}};return function(a){i();b?a():d.push(a)}}(),reformatKeys:function(a){var d,b,i=function(a){return"_"+a.toLowerCase()};for(d in a)b=d.replace(/([A-Z])/g,i),"object"===c.type(a[d])&&(a[d]=c.reformatKeys(a[d])),b!==d&&(a[b]=a[d],delete a[d]);return a},removeClass:function(a,d){if(c.hasClass(a,d)){var b,i,g=c.attrValues(a,"className");b=0;for(i=g.length;b<i;b++)g[b]===
d&&delete g[b];a.className=g.join(" ")}},request:function(a,d,b){var i,g;b=c.extend({fn:c.noop,"return":!1,timeout:null},b);"string"===typeof b.fn?d=c.extend(d,{jsonp:b.fn}):"function"===typeof b.fn&&(i=c.destructing(b.fn),g=c.uniqid("vglnk_jsonp_"),d=c.extend(d,{jsonp:g}),window[g]=c.exceptionLogger(function(){i.apply(this,arguments);window[g]=void 0}),null!==b.timeout&&setTimeout(c.exceptionLogger(i),b.timeout));d=c.extend({format:"jsonp"},d);d=c.toQuery(d);a=a+(d.length?"?":"")+d;return b["return"]?
a:c.traits.cors&&!1!==c.cors(a)?!0:c.jsonp(a)},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(d){var b,c,g=[];b=0;for(c=a.length;b<c;b++)g[b]=a[b];return g}},toQuery:function(a){var d,b="";for(d in a)null!==a[d]&&void 0!==a[d]&&(b+="\x26"+encodeURIComponent(d)+"\x3d"+encodeURIComponent(a[d]));return b.substr(1)},transmitsPII:function(a){return c.containsPII(a+" "+document.referrer)},updateUrl:function(a,d){return c.extend(c.createA(a),d).href},uniqid:function(){var a=
0;return function(d){return(d||"")+(new Date).getTime()+a++}}()});c.traits={basicCompatibility:!(c.browser.blackberry||c.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!(c.browser.ios&&c.browser.version&&(5>c.browser.version||5<c.browser.version)),jsRedirectSetsReferrer:c.browser.aol||!(c.browser.ie||c.browser.opera),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var e,
p,l,v=function(a){var d=a.previousSibling,b=a.nextSibling,i=["",a.textContent,""],g=function(a,d,b){a=a.replace(/\s+/g," ");d=d.replace(/\s+/g," ");b=b.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===d.substr(0,1)&&(d=d.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===d.substr(d.length-1,1)&&(d=d.substr(0,d.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,d,b]};void 0!==i[1]&&(i[0]=d&&3===d.nodeType?d.data:"",i[2]=b&&3===b.nodeType?b.data:"",i=g.apply(this,i),""!==
i[0]&&""!==i[2]&&(i[0]=i[0].split(" ").reverse().slice(0,10+(" "===i[0].substr(i[0].length-1,1)?1:0)).reverse().join(" "),i[2]=i[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(c.cache(a,"params")||{}).type,before:i[0],after:i[2],txt:i[1],loc:location.href,out:c.getActualHref(a),v:2},j.log("info",c.toQuery(a))))},n={};c.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};var m=c.exceptionLogger(function(){var a=!0===document.__v5k;document.__v5k=!0;a||(this.initLibEvents(),this.initNamespace(),
this.initOptions(),c.exceptionLogger(c.bind(this.logException,this),!e.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}),x,s=1,t=[],u=function(){var a=[];x=null;c.each(t,function(d){var b,i=d[0];b=d[1];var g=d[2];if(i=window.vglnk&&window.vglnk[i+"_plugin"]){if((d="function"===c.type(i.setup)?i.setup:null)&&!g){var g=c.clone(c),k=b.key;d(b,g,l,function(){if(k){var a=c.toArray(arguments);a.unshift("custom",k);j.log.apply(this,a)}})}b&&
1===b.mode?delete b.mode:(b="function"===c.type(i.run)?i.run:c.noop(),b())}else a.push(d)});t=a;0<t.length&&(x=setTimeout(c.exceptionLogger(u),Math.min(Math.max(Math.pow(2,++s),100),5E3)))},w=function(a,d){return function(){t.push([a,d,!0]);s=1;clearTimeout(x);u()}},z=c.canonicalizeHostname(document.location),y=c.generateNodeFilter({rels:["norewrite","noskim"],custom:function(a){var d,b="";try{d=a.hostname,b=a.protocol,d.charAt(0)}catch(i){return!0}""!==d&&(d=c.canonicalizeHostname(a));return""===
d||z===d||!b.match(/^https?:$/i)||e.norewrite[d]||!(e.rewrite_original||c.cache(a,"type"))}}),A=c.destructing(function(){var a={left:j.onClick,right:j.onContextmenu},d={left:c.noop,right:c.noop},b=c.traits.windowLevelHandlers?window:document,i=function(b){b=b||window.event;if((b=c.eventLink(b))&&!c.cache(b,"evented"))g(b,j.harmony(c.harmony.LINK_LEVEL_EVENTS)?a:d),c.cache(b,"evented",!0)},g=function(a,d){c.on(a,"click",c.bind(d.left,j));c.on(a,"contextmenu",c.bind(d.right,j))};c.on(b,"copy",c.bind(j.onCopy,
j));c.on(b,"mousedown",i);if(j.harmony(c.harmony.LINK_LEVEL_EVENTS))c.on("DOMReady",function(){c.each(document.links,function(a){c.on(a,"mousedown",i)})});(!c.traits.quirksMode||j.harmony(c.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&g(b,a)}),B,q=!1,C={},D=!1,F=[],E=function(a){if(void 0===a)return F;"function"===c.type(a)&&(F.push({id:c.uniqid(),fn:a}),D&&this.initLinks())};E(function(){D=!0});j={api:function(a,d,b){a=e.api_url+"/"+a;d=c.extend({key:e.key,drKey:e.key?null:e.dr_key},b.basic?{}:{cuid:e.cuid,
loc:location.href,subId:e.sub_id,v:1},d);delete b.basic;d.subId&&d.key!==e.key&&(d.subId=null);return c.request(a,d,b)},addEventListener:function(a,d){this.fire(a,d)},click:function(a,d){d=a.target||d;d=!d||d===window.name||"_top"===d&&window.top===window.self||"_parent"===d&&window.parent===window.self?"_self":d;var b,i,g;"_self"===d?g=window.self:c.traits.crossWindowCommunication&&c.traits.jsRedirectSetsReferrer?(i=window.open("",d),i.focus(),g=i):g=void 0;var k;if("_self"!==d&&(!c.traits.crossWindowCommunication||
!c.traits.jsRedirectSetsReferrer))k="go";else try{if(void 0===g.document)throw!0;k="jsonp"}catch(o){k="go"}b=c.destructing(c.bind(function(){e.time_click&&arguments.length&&this.logTime("clk");var b=c.toArray(arguments);b.unshift(a,g,d);this.onApiClick.apply(this,b)},this));c.cache(this,"link","string"===typeof a?a:c.getActualHref(a));if("string"===typeof a&&(a=c.createA(a,d),!this.processLink(a))||!e.enabled)return b();i=this.clickParams(a,k);this.logTime();e.log_context&&v(a);if("go"===k)this.redirect(this.api("click",
i,{"return":!0}),g,d);else if(g===window.self)this.api("click",i,{fn:b,timeout:e.click_timeout});else{if(c.contextIsAncestor(g))return this.redirect(c.getActualHref(a),g,d);b=c.exceptionLogger(b);setTimeout(function(){b()},e.click_timeout);g.document.open();g.callback=b;g.document.write("\x3chtml\x3e\x3chead\x3e\x3ctitle\x3e"+c.getActualHref(a)+'\x3c/title\x3e\x3cscript type\x3d"text/javascript" src\x3d"'+this.api("click",i,{fn:"callback","return":!0})+'"\x3e\x3c/script\x3e\x3c/head\x3e\x3c/html\x3e');
g.document.close()}},clickParams:function(a,b){var h=c.extend(c.cache(a,"params"),{format:b,libId:e.library_id,out:c.getActualHref(a),ref:document.referrer||null,reaf:e.reaffiliate||null,title:document.title,txt:a.innerHTML});128<h.txt.length&&(h.txt=h.txt.replace(/<[^>]+>/g,""),h.txt=128<h.txt.length?h.txt.substr(0,125)+"...":h.txt);return h},enabled:function(){if(e.enabled&&p!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))e.enabled=!1;return e.enabled},expose:function(a,
b){if(b=b||this[a])"function"===typeof b?b=c.exceptionLogger(c.bind(b,this)):"object"===typeof b&&(b=c.clone(b)),l[a]||(l[a]=b)},fire:function(a,b){a=a.toLowerCase();var h=n[a]||{fired:!1,listeners:[]};"function"===typeof b?h.fired?b({type:a}):h.listeners.push(b):(h.fired=!0,c.each(h.listeners,function(b){"function"===typeof b&&b({type:a})}),h.listeners=[]);n[a]=h},handleRightClick:function(a,b){if(e.rewrite_modified&&a&&b)switch(b){case "setup":c.cache(a,"href")||c.cache(a,"href",a.href);a.href=
this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(c.exceptionLogger(c.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=c.cache(a,"href"),c.cache(a,"href",null)}},harmony:function(a){return e.harmony_level<=a},init:m,initApi:function(){var a,b={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(b[a]=window.vglnk[a]);l=p[f]=c.noop;this.expose("click");this.expose("link",function(a){"element"===c.type(a)&&a.href&&j.processLink(a)});
this.expose("$",c.clone(c));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return j.registerProcessor.apply(j,arguments)});c.extend(l,l===window.vglnk?b:{})},initDRApi:function(){var a=!1;window.DrivingRevenue=c.exceptionLogger(c.destructing(c.bind(function(){a=!0;e.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));c.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initLibEvents:function(){c.on(j);
c.ready(c.bind(function(){this.fire("DOMReady")},this))},initNamespace:function(){window.vglnk&&window.vglnk.key&&(f="vglnk");var a=window,b=f.split("."),c;for(f=b.pop();0<b.length;)c=b.shift(),a[c]=a[c]||{},a=a[c];p=a;l=p[f]=p[f]||{}},initOptions:function(){var a;this.initLegacyOptions();e=c.extend(this.publicOptions({api_url:"//api.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:c.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,harmony_level:0,rewrite_original:!0,
rewrite_modified:!1}),e,l,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in e)"_plugin"===a.substr(-7)&&delete e[a]},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(l[b[a]]=window[a],"vglnk_domain"===a&&(l[b[a]]+=
"/api"))},initLegacyCallbacks:function(){var a,b={vl_cB:c.bind(this.onApiClick,this),vl_disable:function(){e.enabled=!1}};for(a in b)window[a]=b[a]},initLinks:function(){c.each(c.toArray(document.links),c.bind(this.processLink,this))},initPlugins:function(a){for(var b in a)"object"===typeof a[b]&&!1!==a[b].enabled&&(t.push([b,a[b]]),1===a[b].mode&&this.expose("init_"+b,w(b,a[b])));u()},initProcessors:function(){this.registerProcessor(function(a){var b;b=c.createA(e.api_url);if("/api/click"===a.pathname&&
(a.hostname===b.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))b=c.fromQuery(a.search),void 0!==b.out&&(a.href=b.out,delete b.out,c.cache(a,"params",b))});this.registerProcessor(function(a){e.nofollow[a.href]&&!c.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&c.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},
isRewritable:function(a){return y(a,{ancestors:!1})},initEvents:A,log:function(a,b,h,i){var g,k=c.toQuery({nocache:c.uniqid()});g="pixel.gif";if("custom"===a)k+="\x26"+c.toQuery({key:b,type:h}),c.each("array"===c.type(i)?i:[i],function(a){c.each(["e","i","o"],function(b){delete a[b]});k+="\x26"+c.toQuery(a)});else{k+="\x26"+c.toQuery({key:e.key,drKey:e.key?null:e.dr_key});if("time"===a)g="time.gif",a={libId:e.library_id,time:h,type:b};else if("exception"===a)a={e:b,o:h};else if("info"===a)a={i:b};
else return;k+="\x26"+c.toQuery(a)}g=e.api_url+"/"+g+"?"+k;c.transmitsPII(g)||(c.createEl("img").src=g)},logException:function(a){if(e.debug){var b={link:c.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?b.message=a:b=c.extend(b,a);this.log("exception",a,c.toQuery(b))}},logTime:function(a){0===arguments.length?B=(new Date).getTime():this.log("time",a,(new Date).getTime()-B)},onApiClick:function(a,b,h,i,g){var k=i||c.getActualHref(a);i=c.bind(function(){this.redirect(k,
b,h)},this);"object"===typeof g&&(g.tracking||g.image)?(a=c.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(a),setTimeout(c.exceptionLogger(i),g.timeout||e.hop_timeout)):i()},onApiPing:function(a,b,h,i,g,k){e.rewrite_original=!1;g=c.reformatKeys(g||{});var o,f;i=function(a){var b={},d=function(a){c.isArray(a)?b[a[0]]=a[1]:b[a]=1};c.isArray(a)&&c.each(a,d);return b};f=c.extend(e.plugins,g.plugins);e=c.extend(e,g);delete e.plugins;
e.library_id=a;e.click_timeout=b;e.time_ping&&this.logTime("png");"array"===c.type(e.testing_js)&&0<e.testing_js.length&&c.each(e.testing_js,function(a){c.jsonp(a)});c.extend(e.norewrite,i(h));c.extend(e.nofollow,i(k));for(o in e)"on"===o.toLowerCase().substr(0,2)&&(2<o.length&&"function"===c.type(e[o]))&&(c.on(j,o.toLowerCase().substr(2),c.bind(e[o],window)),delete e[o]);this.initPlugins(f);this.initLinks();this.initEvents();this.fire("libready")},onClick:function(a){a=a||window.event;var b=a.ctrlKey||
a.metaKey||a.altKey||a.shiftKey,h=a.which&&1===a.which||0===a.button,i=c.eventLink(a);if(i&&this.isRewritable(i)&&!b&&h&&!c.isDefaultPrevented(a))return this.click(i),c.preventDefault(a)},onContextmenu:function(a){(a=c.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(){var a,b,h,i,g=[];if(window.getSelection){h=window.getSelection();a=0;for(b=h.rangeCount;a<b;a++){try{i=h.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,
"\n")}catch(k){}0<i.length&&128>=i.length&&g.push(i)}}c.each(g,function(a){j.log("info",c.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(e[a]=b);return e[a]},ping:function(){if(!q&&(e.key||e.dr_key)){var a={ref:document.referrer||null};q=!0;c.transmitsPII(this.api("ping",a,{"return":!0}))||(this.logTime(),this.api("ping",a,{fn:c.bind(this.onApiPing,this)}))}},processLink:function(a){if(this.isRewritable(a)){var b=c.cache(a,
"processors")||{};c.each(this.registerProcessor(),function(c){b[c.id]||c.fn(a);b[c.id]=!0});c.cache(a,"processors",b);return a}},publicOptions:function(a){"object"===c.type(a)&&(C=a);return c.extend({},C)},redirect:function(a,b,h){!c.traits.crossWindowCommunication&&!b?(h=window.open(a,h),h.focus()):c.traits.jsRedirectSetsReferrer?setTimeout(c.exceptionLogger(function(){!b||b===window.self?window.location=a:c.contextIsAncestor(b)?b.location=a:b.location.replace(a)}),0):("_blank"===h&&(h=c.uniqid("win_")),
h=c.createA(a,h),h.rel="norewrite",document.body.appendChild(h),h.click(),h.parentNode.removeChild(h))},registerProcessor:E};j.init();try{delete window.vglnk_self}catch(b){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};window.vglnk.link_affiliation_plugin=function(){var f;return{setup:function(j,c,e){f=e},run:function(){f.opt("rewrite_original",!0)}}}();window.vglnk=window.vglnk||{};
window.vglnk.modified_clicks_plugin=function(){var f;return{setup:function(j,c,e){f=e},run:function(){f.opt("rewrite_modified",!0)}}}();window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(){var f,j,c={key:null},e={init:function(){f.each(this.getDRSearchForms(),function(c){if(!f.cache(c,"evented")){var l=e.getInput(c),j=function(){l.value||f.css(l,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};f.cache(c,"evented",!0);c.onsubmit=null;l.onfocus=null;l.onblur=null;f.on(l,"focus",function(){f.css(l,{"background-image":"none"})});f.on(l,"blur",j);j();f.on(c,"submit",function(f){e.onSubmit(f,c)})}})},getDRSearchForms:function(){var c=
[];f.each(document.getElementsByTagName("form"),function(f){e.getInput(f)&&f.id.match(/^DR-ebay-search(CSS|2)?$/i)&&c.push(f)});return c},getInput:function(c){return c.p||c.q2},onSubmit:function(p,l){p=p||window.event;var v="http://shop.ebay.com/i.html?"+f.toQuery({_nkw:e.getInput(l).value}),v=f.createA(v,"_blank");f.cache(v,"params",{key:c.key});j.click(v);return f.preventDefault(p)}};return{setup:function(e,l,v){f=l;j=v;c=f.extend(c,e)},run:function(){c.key&&(e.init(),f.on("DOMReady",f.bind(e.init,
e)))}}}();window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(){var f,j,c={level:null};return{setup:function(e,p,l){f=e;j=l;c=f.extend(c,p)},run:function(){var e=parseInt(c.level,10);isFinite(e)&&j.opt("harmony_level",e)}}}();window.vglnk=window.vglnk||{};
window.vglnk.partner_integration_plugin=function(){var f,j,c={eb_campaign:5337208431,eb_cid:null,eb_gid:null,eb_group:null,eb_pct:0,eb_rotation:"711-53200-19255-0"},e=/(^|\.)ebay\.com$/,p=/(^|\.)rover\.ebay\.com$/,l={injectPixel:function(){if(c.eb_cid&&c.eb_campaign&&c.eb_rotation&&"number"===f.type(c.eb_gid)&&isFinite(c.eb_gid)&&0<=c.eb_gid){var e,n="//rover.ebay.com/roverimp/1/"+encodeURIComponent(c.eb_rotation)+"/1",m={campid:c.eb_campaign,ff19:c.eb_cid,ff20:c.eb_gid,mpt:Math.floor(99999999*Math.random()),
pub:5574713606,toolid:2E4};e=f.createEl("img",{src:n+"?"+f.toQuery(m)},{border:"none",height:0,width:0,position:"absolute",zIndex:-1});f.on("DOMReady",function(){document.body&&document.body.appendChild(e)})}},expandTruncatedUrl:function(c,e){var f;f=e.textContent||e.innerText;if(f&&(-1!==f.indexOf("...")||-1!==f.indexOf("\u2026"))){var j=f.split("...")[0].split("\u2026")[0],l=c.replace(/^http:\/\//i,"");f=j.length<c.length&&c.substr(0,j.length)===j||j.length<l.length&&l.substr(0,j.length)===j&&-1!==
f.indexOf("/")}else f=void 0;if(f){for(;f=e.firstChild;)e.removeChild(f);e.appendChild(document.createTextNode(c))}},shouldBeUnlinked:function(c,n){var m=f.canonicalizeHostname(c);return e.test(m)&&("inserted"===f.cache(n,"type")||!p.test(m))},unlink:function(c){var e,m,j=!0,l=f.getActualHref(c);if(this.shouldBeUnlinked(l,c)){e=document.createDocumentFragment();if(c.parentNode){for(;m=c.firstChild;)j=j&&3===m.nodeType,e.appendChild(m);j&&this.expandTruncatedUrl(l,e);c.parentNode.insertBefore(e,c);
c.parentNode.removeChild(c)}f.cache(c,"unlinked",!0)}}};return{setup:function(e,n,m){f=n;j=m;c=f.extend(c,e);null===c.eb_group&&(c.eb_group=c.eb_gid/10<c.eb_pct?1:0)},run:function(){l.injectPixel();1===c.eb_group&&j.registerProcessor(f.bind(l.unlink,l))}}}();window.vglnk=window.vglnk||{};
window.vglnk.product_linker_plugin=function(){var f,j,c,e={},p,l,v=null,n={},m,x=0,s=0,t=0,u=0,w={setup:function(z,y,A,B){f=y;j=A;c=B;e=f.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},z);if(e.key){f=f.extend(f,{matches:window.vglnk.Sizzle.matchesSelector||function(){return!0},select:window.vglnk.Sizzle||function(){return[]}});p={bbp:{id_finder:["li",
/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content, .postbody .signature"},ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^\x3d'body'], .post_inner .signature"},vb3:{id_finder:["td",/^td_post_(\d+)$/],scope:"td[id^\x3d'td_post_'] div[id^\x3d'post_message_'],td[id^\x3d'td_post_'] div[id^\x3d'post_message_'] ~ div:not([class])"},
vb4:{id_finder:["li",/^post_(\d+)$/],scope:".postbody .content, .postbody .signature, .post-content, ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}}[e.platform]||{};var q={timing:!1,data:e.link_phrases?!1:e.link_urls},C=function(c){var b=m.test(c.data),a=c.parentNode;if(b)for(var d=c,h,i,g,b=function(a,b){var d,c,h,g,i,k,o,m,j,E,u=function(b){j.parentNode.insertBefore(a,j);j.parentNode.removeChild(j);return b};j=f.createEl("span");a.parentNode.insertBefore(j,
a);j.appendChild(a);E=f.geometry(j);if(e.proximity||e.same_proximity)for(k in n)if((o=n[k].links)&&!(n[k]===b&&!e.same_proximity||n[k]!==b&&!e.proximity)){m=n[k]===b?Math.max(e.same_proximity,e.proximity):e.proximity;d=0;for(c=o.length;d<c;d++){i=o[d].segments;h=0;for(g=i.length;h<g;h++){var l=i[h].geometry,p=E,w=m,l=f.extend({},l);l.x1-=w;l.y1-=w;l.x2+=w;l.y2+=w;if(l.x1<p.x2&&l.x2>p.x1&&l.y1<p.y2&&l.y2>p.y1)return u(!1)}}}return u(!0)};d&&d.data&&Boolean(i=d.data.match(m));){h=i[0];g=i.slice(1).join("");
c=n[g.toLowerCase()];h=d.data.indexOf(h)+h.length-g.length;0<h&&(d=d.splitText(h));h=d.length<=g.length?null:d.splitText(g.length);g&&!c&&(c={url:g.match(/^https?:\/\//i)?g:"http://"+g,type:"U"});var k;if(k=g){var o=k=void 0;k=!c||!e.per_phrase||!c.count||c.count<e.per_phrase;o=!e.per_page||x<e.per_page;k=k&&o&&b(d,c)}if(k&&(k=c,o=void 0,o=f.createEl("a"),o.innerHTML=g.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"\x3cspan\x3e$1\x3c/span\x3e"),o.className="vglnk",f.cache(o,"type","inserted"),f.cache(o,"phrase",
g),e.ui&&(o.title="Link added by VigLink"),l.initLink(o,k),g=o,!f.cache(g,"unlinked"))){"U"===c.type?u++:"L"===c.type.toUpperCase()?s++:t++;a.insertBefore(g,d);a.removeChild(d);var d=c,j=o=k=void 0,p=void 0,q={el:g,segments:[]};g=g.getElementsByTagName("span");var w={els:[]};k=0;for(o=g.length;k<o;k++)j=g[k],void 0===p||j.offsetTop===p.offsetTop?w.els.push(j):(q.segments.push(w),w={els:[j]}),p=j;w.geometry=f.geometry.apply(f,w.els);q.segments.push(w);d.links=d.links||[];d.links.push(q);c.count++;
x++}d=h}},D=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(c){return f.matches(c,"a[href]")}}),F=function(c){var b;if(c){if(D(c,{ancestors:!1,self:!0}))for(b=c.firstChild;b;)c=b.nextSibling,1===b.nodeType?F(b):3===b.nodeType&&C(b),b=c}else f.each(f.select(e.scope),function(a){D(a,{ancestors:!0,self:!1})&&F(a)})};l={addPhrasesToMatcher:function(c){var b=
"";"regexp"===f.type(c)?b=c.source:"array"===f.type(c)&&(b="(?:^|[\\s\"'\\(])("+f.map(c,f.escapeRegExp).join("|")+")(?\x3d\\s|\\W*$|\\W{2})");""!==b&&(m=RegExp(m?"(?:"+b+"|"+m.source+")":b,"i"))},focusLink:function(c){c.id||(c.id=f.uniqid("vl-link-"));location.href.hash="#"+c.id;window.scrollBy(0,-150)},getPhrases:function(c){j.api("insert",f.extend(l.getPartnerParams(),{cat:e.cat,mode:e.mode,pt:e.platform,ps:e.product_source,i:c?c.join("|"):null,u:location.href,type:e.type}),{fn:f.bind(l.onInsertApi,
l)})},getPartnerParams:function(){var c,b,a=j.opt("partner"),d={};for(c in a)break;if(c)for(b in a[c])d[c+"_"+b]=a[c][b];return d},getPostIDs:function(){var c=[],b=p?p.id_finder:null;b&&f.each(f.select(b[0]),function(a){var d=b[2]||"id";(a=a[d]?a[d].match(b[1]):null)&&c.push(a[1])});return c.length?c:null},initLink:function(c,b,a){if(a=e.link_target||a)c.target=a;c.rel="nofollow";c.href||(c.href=b.url);f.cache(c,"params",{exp:v,key:e.key,mid:b.mid,type:b.type||null});f.cache(c,"href",c.href);j.link(c)},
insertLinks:function(c){q=f.extend(q,c);q.timing&&(q.data&&m)&&(F(),l.log())},loadPhrases:function(c){var b,a,d,h=[];b=0;for(a=c.length;b<a;b++)d=c[b],d.phrase&&d.url&&(d.phrase=d.phrase.toLowerCase(),n[d.phrase]||(h.push(d.phrase),n[d.phrase]={count:n[d.phrase]?n[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||""}));0<h.length&&this.addPhrasesToMatcher(h);this.insertLinks({data:!0})},log:function(){var e,b,a={heavy:[],lite:[]},d=function(a,b){return b.split(",")[0]-a.split(",")[0]};
for(e in n)b=parseInt(n[e].count,10),0<b&&(b=[b,e.replace(/\|/g,"%7C")].join(),a["L"===n[e].type.toUpperCase()?"lite":"heavy"].push(b));a.lite.sort(d);a.heavy.sort(d);c("insert",[{ct:x,cl:s,ch:t,cu:u,exp:v},{pl:a.lite.join("|")},{ph:a.heavy.join("|")}])},onInsertApi:function(c){"object"===f.type(c)&&(v=c.exp,c.results&&this.loadPhrases(c.results))},setup:function(){var c=f.bind(function(){this.getPhrases(this.getPostIDs())},this);e.scope=e.scope||p.scope||"body";e.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()\x3c\x3e]+|\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\))+(?:\\((?:[^\\s()\x3c\x3e]|(?:\\([^\\s()\x3c\x3e]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,\x3c\x3e?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"));if(e.link_phrases)if(!e.platform||"full"===e.platform)c();else f.on("DOMReady",c)}};l.setup()}else w.run=f.noop},run:function(){f.on("DOMReady",function(){l.insertLinks({timing:!0})})}};return w}();window.vglnk=window.vglnk||{};
window.vglnk.link_optimization_plugin=function(){var f,j,c={},e,p,l={},v={setup:function(n,m,x){f=m;j=x;c=f.extend({platform:null,api_url:f.updateUrl(j.opt("api_url"),{pathname:"/api/optimize"}),key:j.opt("key")},n);if(!c.api_url||!c.key)v.run=f.noop;else{f=f.extend(f,{select:window.vglnk.Sizzle||function(){return[]}});e={bbp:{id_finder:["li",/^post-(\d+)$/]},hdlr:{id_finder:["div",/^post_(\d+)$/]},ipb:{id_finder:["div",/^post_id_(\d+)$/]},phpb:{id_finder:["div.post",/^p(\d+)$/]},ubb:{id_finder:["a",
/^Post(\d+)$/,"name"]},vb3:{id_finder:["td",/^td_post_(\d+)$/]},vb4:{id_finder:["li",/^post_(\d+)$/]},wppr:{id_finder:["div",/^post-(\d+)$/]}}[c.platform]||{};var s=function(c){var e=c.textContent||c.innerText;c=f.canonicalizeHostname(c);e=f.createEl("a",{href:e});return f.canonicalizeHostname(e)===c},t=f.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(c,e){return e?Boolean(f.cache(c,"type")):!1}});p={getLinks:function(e){f.request(c.api_url,{key:c.key,pt:c.platform,
i:e?e.join("|"):null,u:location.href},{fn:f.bind(p.onOptimizeApi,p)})},getPostIDs:function(){var c=[],j=e?e.id_finder:null;j&&f.each(f.select(j[0]),function(e){var f=j[2]||"id";(e=e[f]?e[f].match(j[1]):null)&&c.push(e[1])});return c.length?c:null},onOptimizeApi:function(c){"object"===f.type(c)&&"object"===f.type(c.optLinks)&&(l=c.optLinks,j.registerProcessor(f.bind(this.optimizeLink,p)))},optimizeLink:function(c){var e=l[c.href],j=s(c);if(e&&t(c)){var n=c.textContent||c.innerText,m;if(!(m=c.href===
n))s(c)?(m=f.fromQuery(c.search),m=f.find(m,function(c){return c===n})):m=!1;if(m){for(j=e.optLink;m=c.firstChild;)c.removeChild(m);c.appendChild(document.createTextNode(j))}else if(j)return;f.cache(c,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});c.href=e.optLink}},setup:function(){var e=f.bind(function(){this.getLinks(this.getPostIDs())},this);if(!c.platform||"full"===c.platform)e();else f.on("DOMReady",e)}};p.setup()}},run:function(){}};return v}();
(function(){function f(b,a,c,h,i,g){i=0;for(var e=h.length;i<e;i++){var f=h[i];if(f){for(var j=!1,f=f[b];f;){if(f.sizcache===c){j=h[f.sizset];break}1===f.nodeType&&!g&&(f.sizcache=c,f.sizset=i);if(f.nodeName.toLowerCase()===a){j=f;break}f=f[b]}h[i]=j}}}function j(b,a,c,h,i,g){i=0;for(var e=h.length;i<e;i++){var f=h[i];if(f){for(var j=!1,f=f[b];f;){if(f.sizcache===c){j=h[f.sizset];break}if(1===f.nodeType)if(g||(f.sizcache=c,f.sizset=i),"string"!==typeof a){if(f===a){j=!0;break}}else if(0<n.filter(a,
[f]).length){j=f;break}f=f[b]}h[i]=j}}}var c=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,e=0,p=Object.prototype.toString,l=!1,v=!0;[0,0].sort(function(){v=!1;return 0});var n=function(b,a,d,h){d=d||[];var i=a=a||document;if(1!==a.nodeType&&9!==a.nodeType)return[];if(!b||"string"!==typeof b)return d;var g,e,f,j,l,s=!0,q=n.isXML(a),r=[],t=b;do if(c.exec(""),g=c.exec(t))if(t=g[3],r.push(g[1]),g[2]){j=g[3];break}while(g);
if(1<r.length&&x.exec(b))if(2===r.length&&m.relative[r[0]])e=E(r[0]+r[1],a);else for(e=m.relative[r[0]]?[a]:n(r.shift(),a);r.length;)b=r.shift(),m.relative[b]&&(b+=r.shift()),e=E(b,e);else if(!h&&(1<r.length&&9===a.nodeType&&!q&&m.match.ID.test(r[0])&&!m.match.ID.test(r[r.length-1]))&&(g=n.find(r.shift(),a,q),a=g.expr?n.filter(g.expr,g.set)[0]:g.set[0]),a){g=h?{expr:r.pop(),set:u(h)}:n.find(r.pop(),1===r.length&&("~"===r[0]||"+"===r[0])&&a.parentNode?a.parentNode:a,q);e=g.expr?n.filter(g.expr,g.set):
g.set;for(0<r.length?f=u(e):s=!1;r.length;)g=l=r.pop(),m.relative[l]?g=r.pop():l="",null==g&&(g=a),m.relative[l](f,g,q)}else f=[];f||(f=e);f||n.error(l||b);if("[object Array]"===p.call(f))if(s)if(a&&1===a.nodeType)for(b=0;null!=f[b];b++)f[b]&&(!0===f[b]||1===f[b].nodeType&&n.contains(a,f[b]))&&d.push(e[b]);else for(b=0;null!=f[b];b++)f[b]&&1===f[b].nodeType&&d.push(e[b]);else d.push.apply(d,f);else u(f,d);j&&(n(j,i,d,h),n.uniqueSort(d));return d};n.uniqueSort=function(b){if(z&&(l=v,b.sort(z),l))for(var a=
1;a<b.length;a++)b[a]===b[a-1]&&b.splice(a--,1);return b};n.matches=function(b,a){return n(b,null,null,a)};n.matchesSelector=function(b,a){return 0<n(a,null,null,[b]).length};n.find=function(b,a,c){var h;if(!b)return[];for(var i=0,g=m.order.length;i<g;i++){var e,f=m.order[i];if(e=m.leftMatch[f].exec(b)){var j=e[1];e.splice(1,1);if("\\"!==j.substr(j.length-1)&&(e[1]=(e[1]||"").replace(/\\/g,""),h=m.find[f](e,a,c),null!=h)){b=b.replace(m.match[f],"");break}}}h||(h="undefined"!==typeof a.getElementsByTagName?
a.getElementsByTagName("*"):[]);return{set:h,expr:b}};n.filter=function(b,a,c,h){for(var i,g,e=b,f=[],j=a,l=a&&a[0]&&n.isXML(a[0]);b&&a.length;){for(var p in m.filter)if(null!=(i=m.leftMatch[p].exec(b))&&i[2]){var q,r,s=m.filter[p];r=i[1];g=!1;i.splice(1,1);if("\\"!==r.substr(r.length-1)){j===f&&(f=[]);if(m.preFilter[p])if(i=m.preFilter[p](i,j,c,f,h,l)){if(!0===i)continue}else g=q=!0;if(i)for(var t=0;null!=(r=j[t]);t++)if(r){q=s(r,i,t,j);var u=h^!!q;c&&null!=q?u?g=!0:j[t]=!1:u&&(f.push(r),g=!0)}if(void 0!==
q){c||(j=f);b=b.replace(m.match[p],"");if(!g)return[];break}}}if(b===e)if(null==g)n.error(b);else break;e=b}return j};n.error=function(b){throw"Syntax error, unrecognized expression: "+b;};var m=n.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,
CHILD:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(b){return b.getAttribute("href")}},relative:{"+":function(b,a){var c="string"===typeof a,h=c&&!/\W/.test(a),c=c&&!h;h&&(a=a.toLowerCase());for(var h=0,i=
b.length,g;h<i;h++)if(g=b[h]){for(;(g=g.previousSibling)&&1!==g.nodeType;);b[h]=c||g&&g.nodeName.toLowerCase()===a?g||!1:g===a}c&&n.filter(a,b,!0)},"\x3e":function(b,a){var c,h="string"===typeof a,i=0,g=b.length;if(h&&!/\W/.test(a))for(a=a.toLowerCase();i<g;i++){if(c=b[i])c=c.parentNode,b[i]=c.nodeName.toLowerCase()===a?c:!1}else{for(;i<g;i++)(c=b[i])&&(b[i]=h?c.parentNode:c.parentNode===a);h&&n.filter(a,b,!0)}},"":function(b,a,c){var h,i=e++,g=j;"string"===typeof a&&!/\W/.test(a)&&(h=a=a.toLowerCase(),
g=f);g("parentNode",a,i,b,h,c)},"~":function(b,a,c){var h,i=e++,g=j;"string"===typeof a&&!/\W/.test(a)&&(h=a=a.toLowerCase(),g=f);g("previousSibling",a,i,b,h,c)}},find:{ID:function(b,a,c){if("undefined"!==typeof a.getElementById&&!c)return(b=a.getElementById(b[1]))&&b.parentNode?[b]:[]},NAME:function(b,a){if("undefined"!==typeof a.getElementsByName){for(var c=[],h=a.getElementsByName(b[1]),i=0,g=h.length;i<g;i++)h[i].getAttribute("name")===b[1]&&c.push(h[i]);return 0===c.length?null:c}},TAG:function(b,
a){if("undefined"!==typeof a.getElementsByTagName)return a.getElementsByTagName(b[1])}},preFilter:{CLASS:function(b,a,c,h,i,g){b=" "+b[1].replace(/\\/g,"")+" ";if(g)return b;g=0;for(var e;null!=(e=a[g]);g++)e&&(i^(e.className&&0<=(" "+e.className+" ").replace(/[\t\n\r]/g," ").indexOf(b))?c||h.push(e):c&&(a[g]=!1));return!1},ID:function(b){return b[1].replace(/\\/g,"")},TAG:function(b){return b[1].toLowerCase()},CHILD:function(b){if("nth"===b[1]){b[2]||n.error(b[0]);b[2]=b[2].replace(/^\+|\s*/g,"");
var a=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec("even"===b[2]&&"2n"||"odd"===b[2]&&"2n+1"||!/\D/.test(b[2])&&"0n+"+b[2]||b[2]);b[2]=a[1]+(a[2]||1)-0;b[3]=a[3]-0}else b[2]&&n.error(b[0]);b[0]=e++;return b},ATTR:function(b,a,c,h,i,g){a=b[1]=b[1].replace(/\\/g,"");!g&&m.attrMap[a]&&(b[1]=m.attrMap[a]);b[4]=(b[4]||b[5]||"").replace(/\\/g,"");"~\x3d"===b[2]&&(b[4]=" "+b[4]+" ");return b},PSEUDO:function(b,a,d,h,i){if("not"===b[1])if(1<(c.exec(b[3])||"").length||/^\w/.test(b[3]))b[3]=n(b[3],null,null,a);else return b=
n.filter(b[3],a,d,1^i),d||h.push.apply(h,b),!1;else if(m.match.POS.test(b[0])||m.match.CHILD.test(b[0]))return!0;return b},POS:function(b){b.unshift(!0);return b}},filters:{enabled:function(b){return!1===b.disabled&&"hidden"!==b.type},disabled:function(b){return!0===b.disabled},checked:function(b){return!0===b.checked},selected:function(b){return!0===b.selected},parent:function(b){return!!b.firstChild},empty:function(b){return!b.firstChild},has:function(b,a,c){return!!n(c[3],b).length},header:function(b){return/h\d/i.test(b.nodeName)},
text:function(b){return"text"===b.type},radio:function(b){return"radio"===b.type},checkbox:function(b){return"checkbox"===b.type},file:function(b){return"file"===b.type},password:function(b){return"password"===b.type},submit:function(b){return"submit"===b.type},image:function(b){return"image"===b.type},reset:function(b){return"reset"===b.type},button:function(b){return"button"===b.type||"button"===b.nodeName.toLowerCase()},input:function(b){return/input|select|textarea|button/i.test(b.nodeName)}},
setFilters:{first:function(b,a){return 0===a},last:function(b,a,c,h){return a===h.length-1},even:function(b,a){return 0===a%2},odd:function(b,a){return 1===a%2},lt:function(b,a,c){return a<c[3]-0},gt:function(b,a,c){return a>c[3]-0},nth:function(b,a,c){return c[3]-0===a},eq:function(b,a,c){return c[3]-0===a}},filter:{PSEUDO:function(b,a,c,h){var i=a[1],g=m.filters[i];if(g)return g(b,c,a,h);if("contains"===i)return 0<=(b.textContent||b.innerText||n.getText([b])||"").indexOf(a[3]);if("not"===i){a=a[3];
c=0;for(h=a.length;c<h;c++)if(a[c]===b)return!1;return!0}n.error(i)},CHILD:function(b,a){var c=a[1],h=b;switch(c){case "only":case "first":for(;h=h.previousSibling;)if(1===h.nodeType)return!1;if("first"===c)return!0;h=b;case "last":for(;h=h.nextSibling;)if(1===h.nodeType)return!1;return!0;case "nth":var c=a[2],i=a[3];if(1===c&&0===i)return!0;var g=a[0],e=b.parentNode;if(e&&(e.sizcache!==g||!b.nodeIndex)){for(var f=0,h=e.firstChild;h;h=h.nextSibling)1===h.nodeType&&(h.nodeIndex=++f);e.sizcache=g}h=
b.nodeIndex-i;return 0===c?0===h:0===h%c&&0<=h/c}},ID:function(b,a){return 1===b.nodeType&&b.getAttribute("id")===a},TAG:function(b,a){return"*"===a&&1===b.nodeType||b.nodeName.toLowerCase()===a},CLASS:function(b,a){return-1<(" "+(b.className||b.getAttribute("class"))+" ").indexOf(a)},ATTR:function(b,a){var c=a[1],c=m.attrHandle[c]?m.attrHandle[c](b):null!=b[c]?b[c]:b.getAttribute(c),h=c+"",e=a[2],g=a[4];return null==c?"!\x3d"===e:"\x3d"===e?h===g:"*\x3d"===e?0<=h.indexOf(g):"~\x3d"===e?0<=(" "+h+
" ").indexOf(g):!g?h&&!1!==c:"!\x3d"===e?h!==g:"^\x3d"===e?0===h.indexOf(g):"$\x3d"===e?h.substr(h.length-g.length)===g:"|\x3d"===e?h===g||h.substr(0,g.length+1)===g+"-":!1},POS:function(b,a,c,h){var e=m.setFilters[a[2]];if(e)return e(b,c,a,h)}}},x=m.match.POS,s=function(b,a){return"\\"+(a-0+1)},t;for(t in m.match)m.match[t]=RegExp(m.match[t].source+/(?![^\[]*\])(?![^\(]*\))/.source),m.leftMatch[t]=RegExp(/(^(?:.|\r|\n)*?)/.source+m.match[t].source.replace(/\\(\d+)/g,s));var u=function(b,a){b=Array.prototype.slice.call(b,
0);return a?(a.push.apply(a,b),a):b};try{Array.prototype.slice.call(document.documentElement.childNodes,0)}catch(w){u=function(b,a){var c=0,h=a||[];if("[object Array]"===p.call(b))Array.prototype.push.apply(h,b);else if("number"===typeof b.length)for(var e=b.length;c<e;c++)h.push(b[c]);else for(;b[c];c++)h.push(b[c]);return h}}var z,y;document.documentElement.compareDocumentPosition?z=function(b,a){return b===a?(l=!0,0):!b.compareDocumentPosition||!a.compareDocumentPosition?b.compareDocumentPosition?
-1:1:b.compareDocumentPosition(a)&4?-1:1}:(z=function(b,a){var c,e,f=[],g=[];c=b.parentNode;e=a.parentNode;var k=c;if(b===a)return l=!0,0;if(c===e)return y(b,a);if(c){if(!e)return 1}else return-1;for(;k;)f.unshift(k),k=k.parentNode;for(k=e;k;)g.unshift(k),k=k.parentNode;c=f.length;e=g.length;for(k=0;k<c&&k<e;k++)if(f[k]!==g[k])return y(f[k],g[k]);return k===c?y(b,g[k],-1):y(f[k],a,1)},y=function(b,a,c){if(b===a)return c;for(b=b.nextSibling;b;){if(b===a)return-1;b=b.nextSibling}return 1});n.getText=
function(b){for(var a="",c,e=0;b[e];e++)c=b[e],3===c.nodeType||4===c.nodeType?a+=c.nodeValue:8!==c.nodeType&&(a+=n.getText(c.childNodes));return a};s=document.createElement("div");t="script"+(new Date).getTime();var A=document.documentElement;s.innerHTML="\x3ca name\x3d'"+t+"'/\x3e";A.insertBefore(s,A.firstChild);document.getElementById(t)&&(m.find.ID=function(b,a,c){if("undefined"!==typeof a.getElementById&&!c)return(a=a.getElementById(b[1]))?a.id===b[1]||"undefined"!==typeof a.getAttributeNode&&
a.getAttributeNode("id").nodeValue===b[1]?[a]:void 0:[]},m.filter.ID=function(b,a){var c="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id");return 1===b.nodeType&&c&&c.nodeValue===a});A.removeChild(s);A=s=null;s=document.createElement("div");s.appendChild(document.createComment(""));0<s.getElementsByTagName("*").length&&(m.find.TAG=function(b,a){var c=a.getElementsByTagName(b[1]);if("*"===b[1]){for(var e=[],f=0;c[f];f++)1===c[f].nodeType&&e.push(c[f]);c=e}return c});s.innerHTML="\x3ca href\x3d'#'\x3e\x3c/a\x3e";
s.firstChild&&("undefined"!==typeof s.firstChild.getAttribute&&"#"!==s.firstChild.getAttribute("href"))&&(m.attrHandle.href=function(b){return b.getAttribute("href",2)});s=null;if(document.querySelectorAll){var B=n,s=document.createElement("div");s.innerHTML="\x3cp class\x3d'TEST'\x3e\x3c/p\x3e";if(!(s.querySelectorAll&&0===s.querySelectorAll(".TEST").length)){var n=function(b,a,c,e){a=a||document;if(!e&&!n.isXML(a)){var f=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(b);if(f&&(1===a.nodeType||9===a.nodeType)){if(f[1])return u(a.getElementsByTagName(b),
c);if(f[2]&&m.find.CLASS&&a.getElementsByClassName)return u(a.getElementsByClassName(f[2]),c)}if(9===a.nodeType){if("body"===b&&a.body)return u([a.body],c);if(f&&f[3]){var g=a.getElementById(f[3]);if(g&&g.parentNode){if(g.id===f[3])return u([g],c)}else return u([],c)}try{return u(a.querySelectorAll(b),c)}catch(k){}}else if(1===a.nodeType&&"object"!==a.nodeName.toLowerCase()){var g=(f=a.getAttribute("id"))||"__sizzle__",j=a.parentNode,l=/^\s*[+~]/.test(b);f?g=g.replace(/'/g,"\\$\x26"):a.setAttribute("id",
g);l&&j&&(a=a.parentNode);try{if(!l||j)return u(a.querySelectorAll("[id\x3d'"+g+"'] "+b),c)}catch(p){}finally{f||a.removeAttribute("id")}}}return B(b,a,c,e)},q;for(q in B)n[q]=B[q];s=null}}q=document.documentElement;var C=q.matchesSelector||q.mozMatchesSelector||q.webkitMatchesSelector||q.msMatchesSelector,D=!1;try{C.call(document.documentElement,"[test!\x3d'']:sizzle")}catch(F){D=!0}C&&(n.matchesSelector=function(b,a){a=a.replace(/\=\s*([^'"\]]*)\s*\]/g,"\x3d'$1']");if(!n.isXML(b))try{if(D||!m.match.PSEUDO.test(a)&&
!/!=/.test(a))return C.call(b,a)}catch(c){}return 0<n(a,null,null,[b]).length});q=document.createElement("div");q.innerHTML="\x3cdiv class\x3d'test e'\x3e\x3c/div\x3e\x3cdiv class\x3d'test'\x3e\x3c/div\x3e";q.getElementsByClassName&&0!==q.getElementsByClassName("e").length&&(q.lastChild.className="e",1!==q.getElementsByClassName("e").length&&(m.order.splice(1,0,"CLASS"),m.find.CLASS=function(b,a,c){if("undefined"!==typeof a.getElementsByClassName&&!c)return a.getElementsByClassName(b[1])},q=null));
n.contains=document.documentElement.contains?function(b,a){return b!==a&&(b.contains?b.contains(a):!0)}:document.documentElement.compareDocumentPosition?function(b,a){return!!(b.compareDocumentPosition(a)&16)}:function(){return!1};n.isXML=function(b){return(b=(b?b.ownerDocument||b:0).documentElement)?"HTML"!==b.nodeName:!1};var E=function(b,a){for(var c,e=[],f="",g=a.nodeType?[a]:a;c=m.match.PSEUDO.exec(b);)f+=c[0],b=b.replace(m.match.PSEUDO,"");b=m.relative[b]?b+"*":b;c=0;for(var j=g.length;c<j;c++)n(b,
g[c],e);return n.filter(f,e)};window.vglnk.Sizzle=n})();